name: sportime

services:
  db:
    image: mariadb:11.4
    container_name: sportime_db
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/Santiago}
      - MARIADB_DATABASE=${DB_NAME:-sportime}
      - MARIADB_USER=${DB_USER:-sportime}
      - MARIADB_PASSWORD=${DB_PASSWORD:-sportime123}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root123}
    volumes:
      - db_data:/var/lib/mysql
    networks: [sportime_net]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: sportime_web
    command: ["bash", "/app/entrypoint.sh"]
    volumes:
      - ./web:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - SECRET_KEY=${SECRET_KEY:-dev-super-secreto-cambialo}
      - DEBUG=${DEBUG:-1}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-}
      - DB_NAME=${DB_NAME:-sportime}
      - DB_USER=${DB_USER:-sportime}
      - DB_PASSWORD=${DB_PASSWORD:-sportime123}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root123}
      - DB_HOST=db
      - DB_PORT=3306
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://localhost:8000}
    depends_on:
      - db
    networks: [sportime_net]

  nginx:
    image: nginx:1.27-alpine
    container_name: sportime_nginx
    ports:
      - "8000:80"
    volumes:
      - static_data:/staticfiles
      - media_data:/media
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks: [sportime_net]

volumes:
  db_data:
  static_data:
  media_data:

networks:
  sportime_net:
    driver: bridge
